# Generated by Django 5.2 on 2025-06-06 09:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField(default='Enter Message')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(upload_to='produt_images/')),
                ('short_description', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(default='No Long Description')),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('usage', models.TextField(blank=True, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('manufacturer', models.TextField(blank=True, null=True)),
                ('buy_link', models.URLField(blank=True, null=True)),
                ('seo_title', models.CharField(blank=True, max_length=100, null=True)),
                ('seo_description', models.CharField(blank=True, max_length=160, null=True)),
                ('created', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
