# Generated by Django 5.2 on 2025-06-07 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0005_account'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='account',
            new_name='UserAccount',
        ),
    ]
