# Generated by Django 5.2 on 2025-06-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0006_rename_account_useraccount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='city',
            new_name='username',
        ),
    ]
