# Generated by Django 5.2 on 2025-06-07 09:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0007_rename_city_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
