# Generated by Django 5.2 on 2025-06-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0013_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
